name: check-iptv-channels

on:
  schedule:
    - cron: "0 21 * * *" # каждый день в 00:00 МСК
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg xvfb
          npm install node-fetch@3

      - name: Run check script
        run: |
          xvfb-run -a node scripts/check.js

      - name: Commit results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/channels.json
          git commit -m "Auto-update channel status" || echo "No changes"
          git push
